# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8068826819415dceb06acd5df907523184ae07f895bf8b4e14b7c0e97f1e2200a9a9eebfdfbb9b777f550b5930298e1d144bc39e48d25b7a51f4ba6787af79e6

test:
  secret_key_base: ffc26ace8940ada64e6e5eafa9af4536538f42929fa70c1a63a51e99cfe51e3e6a60dca74109628e6e5db71253b822ec87f33ae18d55aed11a3108aeaeb96022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
